export const selectors = {
  login: {
    emailInput: '[data-test="email"]',
    passwordInput: '[data-test="password"]',
    loginButton: '[data-test="login-button"]',
    errorMessage: '[data-test="error"]',
    logo: ".login_logo",
    registerLink: '[data-test="register-link"]',
    loginContainer: '[data-test="login-container"]',
  },

  register: {
    firstNameInput: '[data-test="register-firstname"]',
    lastNameInput: '[data-test="register-lastname"]',
    emailInput: '[data-test="register-email"]',
    passwordInput: '[data-test="register-password"]',
    confirmPassword: '[data-test="register-confirm-password"]',
    phoneInput: '[data-test="register-phone"]',
    submitButton: '[data-test="register-submit"]',
    successMessage: '[data-test="register-success"]',
    errorMessage: '[data-test="register-error"]',
    loginLink: '[data-test="login-link"]',
  },

  home: {
    pageTitle: '[data-test="home-title"]',
    searchBar: '[data-test="search-input"]',
    searchBtn: '[data-test="search-button"]',
    recentSection: '[data-test="recent-products"]',
    recentProductItem: '[data-test="recent-product-item"]',
    recentProductName: '[data-test="recent-product-name"]',
    recentProductPrice: '[data-test="recent-product-price"]',
    recentAddToCartBtn: '[data-test="recent-add-to-cart"]',
    cartLink: '[data-test="shopping-cart-link"]',
    cartBadge: '[data-test="shopping-cart-badge"]',
    burgerMenu: '[data-test="burger-menu"]',
    logoutLink: '[data-test="logout-link"]',
    profileLink: '[data-test="profile-link"]',
  },

  results: {
    pageTitle: '[data-test="results-title"]',
    searchResults: '[data-test="search-results"]',
    productItem: '[data-test="product-item"]',
    productName: '[data-test="product-name"]',
    productPrice: '[data-test="product-price"]',
    addToCartBtn: '[data-test="add-to-cart"]',
    noResults: '[data-test="no-results"]',
    resultCount: '[data-test="result-count"]',
    sortDropdown: '[data-test="sort-dropdown"]',
    filterSection: '[data-test="filter-section"]',
  },

  product: {
    name: '[data-test="product-name"]',
    description: '[data-test="product-description"]',
    price: '[data-test="product-price"]',
    addToCartBtn: '[data-test="add-to-cart"]',
    removeBtn: '[data-test="remove-from-cart"]',
    quantityInput: '[data-test="quantity-input"]',
    increaseQty: '[data-test="increase-qty"]',
    decreaseQty: '[data-test="decrease-qty"]',
    image: '[data-test="product-image"]',
    backBtn: '[data-test="back-button"]',
    breadcrumb: '[data-test="breadcrumb"]',
    stockStatus: '[data-test="stock-status"]',
  },

  cart: {
    pageTitle: '[data-test="cart-title"]',
    cartItem: '[data-test="cart-item"]',
    cartItemName: '[data-test="cart-item-name"]',
    cartItemPrice: '[data-test="cart-item-price"]',
    cartItemQty: '[data-test="cart-item-quantity"]',
    increaseQtyBtn: '[data-test="increase-qty"]',
    decreaseQtyBtn: '[data-test="decrease-qty"]',
    removeItemBtn: '[data-test="remove-item"]',
    clearCartBtn: '[data-test="clear-cart"]',
    subtotal: '[data-test="cart-subtotal"]',
    checkoutBtn: '[data-test="checkout"]',
    continueShopBtn: '[data-test="continue-shopping"]',
    emptyCartMessage: '[data-test="empty-cart"]',
  },

  checkout: {
    firstName: '[data-test="firstName"]',
    lastName: '[data-test="lastName"]',
    email: '[data-test="checkout-email"]',
    phone: '[data-test="checkout-phone"]',
    address: '[data-test="checkout-address"]',
    city: '[data-test="checkout-city"]',
    postalCode: '[data-test="postalCode"]',
    country: '[data-test="checkout-country"]',
    continueButton: '[data-test="continue"]',
    cancelButton: '[data-test="cancel"]',
    title: '[data-test="title"]',
    errorMessage: '[data-test="error"]',
    orderSummaryItems: '[data-test="order-summary-item"]',
    subtotal: '[data-test="subtotal-label"]',
    tax: '[data-test="tax-label"]',
    total: '[data-test="total-label"]',
    finishButton: '[data-test="finish"]',
    confirmation: '[data-test="complete-header"]',
    confirmationMsg: '[data-test="complete-text"]',
    orderNumber: '[data-test="order-number"]',
    backHome: '[data-test="back-to-home"]',
  },
};
